//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Egorow_Practic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientView
    {
        public string Client { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int SeriesPassport { get; set; }
        public int NumberPassport { get; set; }
        public int Index { get; set; }
        public string Title { get; set; }
        public string Street { get; set; }
        public string Home { get; set; }
        public string Flat { get; set; }
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}
