//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Egorow_Practic
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeView
    {
        public string Employee { get; set; }
        public string Login { get; set; }
        public int idHistory { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public int Id { get; set; }
        public string Input { get; set; }
    }
}
