//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Egorow_Practic
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderView
    {
        public int Id { get; set; }
        public string Client { get; set; }
        public string Service { get; set; }
        public System.DateTime DateCreate { get; set; }
        public System.TimeSpan TimeOrder { get; set; }
        public Nullable<System.DateTime> DateClose { get; set; }
        public int TimeRental { get; set; }
        public string Status { get; set; }
        public string Street { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
