//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Egorow_Practic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.ServiceandOrder = new HashSet<ServiceandOrder>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateCreate { get; set; }
        public System.TimeSpan TimeOrder { get; set; }
        public int idClient { get; set; }
        public int idStatus { get; set; }
        public Nullable<System.DateTime> DateClose { get; set; }
        public int TimeRental { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceandOrder> ServiceandOrder { get; set; }
    }
}
